### ISSUE TITLE
no multiline lua command line via TCP due to node.output() not redirecting error output

### ISSUE THREAD

**Issue by Juul** [sudomesh/disaster-radio-nodemcu#1]
We're currently using the custom-written interpret.lua to implement a lua command line. It is however sub-optimal since it can only handle single-line input, whereas the normal nodemcu serial terminal can handle multi-line input.

You're supposed to be able to use node.input() and node.output() from the nodemcu api to inject input to the interpreter but I was running into an issue where error output would still appear on the serial terminal after calling node.output() and would not be sent to the node.output() callback. 

Looking at the nodemcu code it looks like all calls to puts are defined to be calls to c_puts and c_puts is defined as calls to output_redirect().

output_redirect is part of the nodemcu `node` api module in `app/modules/node.c` and it simply checks if the output has been redirected (with a call to node.output) or not and if not it sends it to `uart0_sendStr()` which is a function in the uart driver `app/driver/uart.c`. 

I can see nothing wrong with this code so now I suspect it might have been an async error where node.output was called to un-redirect the output prematurely (before the error output occurred). More testing needed.

**Comment by Juul** [comment]
We could potentially simply add multi-line support to the existing solution using: http://lua-users.org/wiki/LuaInterpreterInLua

**Comment by Juul** [comment]
Redirecting the error output now seems to be working. We could try switching it back to using the the built-in multiline lua interpreter and see if it works.

**Comment by paidforby** [comment]
moved to arduino see, https://github.com/sudomesh/disaster-radio
