### ISSUE TITLE
serving larger files with webserver is very slow

### ISSUE THREAD

**Issue by Juul** [sudomesh/disaster-radio-nodemcu#2]
Even a 150 kB takes ~10 seconds to serve.

This is because the lua buffersize (LUAL_BUFFERSIZE) is set to 1024 at compile time so we have to repeatedly read 1024 bytes and then send 1024 bytes. We should try recompiling with a higher buffersize.

**Comment by Juul** [comment]
Hm. The relevant file `app/lua/luaconf.h` has this to say:

```
/*
@@ LUAL_BUFFERSIZE is the buffer size used by the lauxlib buffer system.
** Attention: This value should probably not be set higher than 1K.
** The size has direct impact on the C stack size needed be auxlib functions.
** For example: If set to 4K a call to string.gsub will need more than 
** 5k C stack space.
*/
#define LUAL_BUFFERSIZE         256
```
Maybe the solution is to do a bunch of file reads and then send it in one go?

**Comment by paidforby** [comment]
moved away NodeMCU to arduino https://github.com/sudomesh/disaster-radio reopen there if still an issue
