### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by nicopace** [sudomesh/disaster-radio-nodemcu#3]
Hi!

We at LibreRouter project are planning to work on something very similar to this but for other purposes (to have a low power long range network to switch distant routers on and off).
I believe this could be adapted to use the lora network as a backhaul mesh network between the devices, and connect to the disaster radio device to switch routers on and off.
We would like to try it out... is the information here acurate and enougth to reproduce a test environment?
For example, could you publish the schematics of your design?
Thanks!

**Comment by paidforby** [comment]
Hey, we've moved away from using NodeMCU for the disaster-radio firmware and instead are using Arduino, please check out the active project at https://github.com/sudomesh/disaster-radio

**Comment by nicopace** [comment]
Excellent, will do.
Thanks!
