### ISSUE TITLE
Port to ESP32?

### ISSUE THREAD

**Issue by Juul** [sudomesh/disaster-radio-nodemcu#4]
We ran into a memory leak with the web server (TCP server) from nodemcu. There is an effort to port nodemcu to esp32, and it might turn out better than the current nodemcu but maybe we should just got with the official RTOS-based ESP32 firmware and then add eLua to the mix? The [LuaNode](https://github.com/Nicholas3388/LuaNode) repo is an example of someone doing exactly this.

**Comment by paidforby** [comment]
maybe consider reopening in active repo https://github.com/sudomesh/disaster-radio
